language: android
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24
script:
- "./gradlew clean test --continue"
branches:
  only:
  - master
notifications:
  slack:
    secure: sCbcQMMfHD+kqMjqQjIb/losC8Thsa2+8aAw/qS/mAQnpGCUkb6xeW4tpuSSGjA5uWMh3/TVWvgY4mhA2ZgNfDMfR80tJO9moPdIWruPaiEwe4ZhuibgmhF8qgAR7y4tw30jt0Y1UnSjXcfxIUlb/SV9voajvJNr7y7x1Ltjiu7619fnwBnURJ3TApkBLwsmohz9SWbULL1GYWc6CWT50rcE7MQWONubRZa4tnYwBQ7qZ6z2WeIgBdwSElyS5qczsMObq8ql6p8o1nM/ultGv2xehNyjwpAX73cLfKNS6KWD89EXtt6UV+Sy22Wbjv0W68pSJ6V28hKodMAxhNEBAfsN24rZ1FlS+B2QXrD32wobLbbX9tFci2tm9VSRLJP2V7u4byEeTyo7mpCVYvpWbPHZHZsO6X+q/ttMM2DzFs4/uthPPqr4wma7h2rfdMv4m4fpLGBb4sdgd1Lal3P+TddN0qFyZLYfqhCrBLR0hwHRT/yaSog17SOwKR/qevKVHsspnLnOWyI6Ern2FpJ+23TuRXK+1Ld8t7PNKbp2mMTA+IU7gCycC5tbH+SuEIIcM51J/0pT1WB3AnEkoCzgKb7FBWZOdIdjNgZxHJQDBOZ5nWkgFrYyGjduwj0h7wI1xBMSUs0ysRyw7Z1tjO4rZYyzPOfThk86/TQv2uYZg4M=
